CREATE TABLE LINE_ITEMS (
    LINE_ID NUMBER(5, 0),
    QUANTITY NUMBER(3, 0) NOT NULL,
    ITEM_ID NUMBER(5, 0),
    ORDER_ID NUMBER(5, 0),
    CONSTRAINT LINE_PK PRIMARY KEY (LINE_ID),
    CONSTRAINT LINE_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);