CREATE TABLE ORDERS (
    ORDER_ID NUMBER(5, 0),
    PLACED_AT DATE,
    CORRELATION_ID VARCHAR2(50) NOT NULL,
    RESTAURANT_ID NUMBER(5, 0),
    ORDER_STATUS VARCHAR2(20) NOT NULL,
    CONSTRAINT ORDER_PK PRIMARY KEY (ORDER_ID),
    CONSTRAINT ORDER_FK FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS (RESTAURANT_ID)
);